set TO 'addons/input_prompts/icons'
set DEF 'Double'
echo "Copy xbox assets from $FROM to $TO"

# XBox icons
set FROM_XBOX "$FROM/Xbox Series/$DEF"
set TO_XBOX "$TO/xbox"
cp $FROM_XBOX/xbox_button_color_a.png $TO_XBOX/a.png
cp $FROM_XBOX/xbox_button_color_b.png $TO_XBOX/b.png
cp $FROM_XBOX/xbox_button_color_x.png $TO_XBOX/x.png
cp $FROM_XBOX/xbox_button_color_y.png $TO_XBOX/y.png
cp $FROM_XBOX/xbox_dpad_round_down.png $TO_XBOX/down.png
cp $FROM_XBOX/xbox_dpad_round_up.png $TO_XBOX/up.png
cp $FROM_XBOX/xbox_dpad_round_left.png $TO_XBOX/left.png
cp $FROM_XBOX/xbox_dpad_round_right.png $TO_XBOX/right.png
cp $FROM_XBOX/xbox_lt.png $TO_XBOX/left_trigger.png
cp $FROM_XBOX/xbox_rt.png $TO_XBOX/right_trigger.png
cp $FROM_XBOX/xbox_lb.png $TO_XBOX/left_bumper.png
cp $FROM_XBOX/xbox_rb.png $TO_XBOX/right_bumper.png
cp $FROM_XBOX/xbox_stick_l_press.png $TO_XBOX/left_stick.png
cp $FROM_XBOX/xbox_stick_r_press.png $TO_XBOX/right_stick.png
cp $FROM_XBOX/xbox_button_menu.png $TO_XBOX/menu.png
cp $FROM_XBOX/xbox_button_view.png $TO_XBOX/view.png
cp $FROM_XBOX/xbox_button_share.png $TO_XBOX/share.png
cp $FROM_XBOX/xbox_guide.png $TO_XBOX/xbox.png

# Generic icons
set FROM_GEN "$FROM/Generic/$DEF"
set TO_GEN "$TO/generic"
cp $FROM_GEN/generic_stick_down.png $TO_GEN/left_stick_down.png
cp $FROM_GEN/generic_stick_left.png $TO_GEN/left_stick_left.png
cp $FROM_GEN/generic_stick_right.png $TO_GEN/left_stick_right.png
cp $FROM_GEN/generic_stick_up.png $TO_GEN/left_stick_up.png

# XBox icons used as generic icons
cp $FROM_XBOX/xbox_stick_r_down.png $TO_GEN/right_stick_down.png
cp $FROM_XBOX/xbox_stick_r_left.png $TO_GEN/right_stick_left.png
cp $FROM_XBOX/xbox_stick_r_right.png $TO_GEN/right_stick_right.png
cp $FROM_XBOX/xbox_stick_r_up.png $TO_GEN/right_stick_up.png

# Keyboard icons
set FROM_KEY "$FROM/Keyboard & Mouse/$DEF"
set TO_KEY "$TO/keyboard"
cp $FROM_KEY/keyboard_0.png $TO_KEY/0.png
cp $FROM_KEY/keyboard_1.png $TO_KEY/1.png
cp $FROM_KEY/keyboard_2.png $TO_KEY/2.png
cp $FROM_KEY/keyboard_3.png $TO_KEY/3.png
cp $FROM_KEY/keyboard_4.png $TO_KEY/4.png
cp $FROM_KEY/keyboard_5.png $TO_KEY/5.png
cp $FROM_KEY/keyboard_6.png $TO_KEY/6.png
cp $FROM_KEY/keyboard_7.png $TO_KEY/7.png
cp $FROM_KEY/keyboard_8.png $TO_KEY/8.png
cp $FROM_KEY/keyboard_9.png $TO_KEY/9.png
cp $FROM_KEY/keyboard_alt.png $TO_KEY/alt.png
cp $FROM_KEY/keyboard_a.png $TO_KEY/a.png
cp $FROM_KEY/keyboard_apostrophe.png $TO_KEY/apostrophe.png
cp $FROM_KEY/keyboard_asterisk.png $TO_KEY/asterisk.png
cp $FROM_KEY/keyboard_at.png $TO_KEY/at.png
cp $FROM_KEY/keyboard_slash_back.png $TO_KEY/backslash.png
cp $FROM_KEY/keyboard_backspace.png $TO_KEY/backspace.png
cp $FROM_KEY/keyboard_blank.png $TO_KEY/blank.png
cp $FROM_KEY/keyboard_b.png $TO_KEY/b.png
cp $FROM_KEY/keyboard_capslock.png $TO_KEY/caps.png
cp $FROM_KEY/keyboard_caret.png $TO_KEY/caret.png
cp $FROM_KEY/keyboard_cent.png $TO_KEY/cent.png
cp $FROM_KEY/keyboard_colon.png $TO_KEY/colon.png
cp $FROM_KEY/keyboard_comma.png $TO_KEY/comma.png
cp $FROM_KEY/keyboard_c.png $TO_KEY/c.png
cp $FROM_KEY/keyboard_ctrl.png $TO_KEY/ctrl.png
cp $FROM_KEY/keyboard_delete.png $TO_KEY/del.png
cp $FROM_KEY/keyboard_dollar.png $TO_KEY/dollar.png
cp $FROM_KEY/keyboard_arrow_down.png $TO_KEY/down.png
cp $FROM_KEY/keyboard_d.png $TO_KEY/d.png
cp $FROM_KEY/keyboard_end.png $TO_KEY/end.png
cp $FROM_KEY/keyboard_return.png $TO_KEY/enter_large.png
cp $FROM_KEY/keyboard_numpad_enter.png $TO_KEY/enter_small.png
cp $FROM_KEY/keyboard_enter.png $TO_KEY/enter_wide.png
cp $FROM_KEY/keyboard_e.png $TO_KEY/e.png
cp $FROM_KEY/keyboard_equals.png $TO_KEY/equals.png
cp $FROM_KEY/keyboard_escape.png $TO_KEY/esc.png
cp $FROM_KEY/keyboard_exclamation.png $TO_KEY/exclamation.png
cp $FROM_KEY/keyboard_f10.png $TO_KEY/f10.png
cp $FROM_KEY/keyboard_f11.png $TO_KEY/f11.png
cp $FROM_KEY/keyboard_f12.png $TO_KEY/f12.png
cp $FROM_KEY/keyboard_f1.png $TO_KEY/f1.png
cp $FROM_KEY/keyboard_f2.png $TO_KEY/f2.png
cp $FROM_KEY/keyboard_f3.png $TO_KEY/f3.png
cp $FROM_KEY/keyboard_f4.png $TO_KEY/f4.png
cp $FROM_KEY/keyboard_f5.png $TO_KEY/f5.png
cp $FROM_KEY/keyboard_f6.png $TO_KEY/f6.png
cp $FROM_KEY/keyboard_f7.png $TO_KEY/f7.png
cp $FROM_KEY/keyboard_f8.png $TO_KEY/f8.png
cp $FROM_KEY/keyboard_f9.png $TO_KEY/f9.png
cp $FROM_KEY/keyboard_slash_forward.png $TO_KEY/forward_slash.png
cp $FROM_KEY/keyboard_f.png $TO_KEY/f.png
cp $FROM_KEY/keyboard_g.png $TO_KEY/g.png
cp $FROM_KEY/keyboard_bracket_greater.png $TO_KEY/greater.png
cp $FROM_KEY/keyboard_hash.png $TO_KEY/hash.png
cp $FROM_KEY/keyboard_home.png $TO_KEY/home.png
cp $FROM_KEY/keyboard_h.png $TO_KEY/h.png
cp $FROM_KEY/keyboard_insert.png $TO_KEY/insert.png
cp $FROM_KEY/keyboard_i.png $TO_KEY/i.png
cp $FROM_KEY/keyboard_j.png $TO_KEY/j.png
cp $FROM_KEY/keyboard_k.png $TO_KEY/k.png
cp $FROM_KEY/keyboard_bracket_open.png $TO_KEY/left_brace.png
cp $FROM_KEY/keyboard_left_bracket.png $TO_KEY/left_bracket.png
cp $FROM_KEY/keyboard_left_paren.png $TO_KEY/left_paren.png
cp $FROM_KEY/keyboard_arrow_left.png $TO_KEY/left.png
cp $FROM_KEY/keyboard_bracket_less.png $TO_KEY/less.png
cp $FROM_KEY/keyboard_l.png $TO_KEY/l.png
cp $FROM_KEY/keyboard_media_back.png $TO_KEY/media_back.png
cp $FROM_KEY/keyboard_media_forward.png $TO_KEY/media_forward.png
cp $FROM_KEY/keyboard_media_next.png $TO_KEY/media_next.png
cp $FROM_KEY/keyboard_media_pause.png $TO_KEY/media_pause.png
cp $FROM_KEY/keyboard_media_play.png $TO_KEY/media_play.png
cp $FROM_KEY/keyboard_media_previous.png $TO_KEY/media_previous.png
cp $FROM_KEY/keyboard_media_record.png $TO_KEY/media_record.png
cp $FROM_KEY/keyboard_media_stop.png $TO_KEY/media_stop.png
cp $FROM_KEY/keyboard_meta.png $TO_KEY/meta.png
cp $FROM_KEY/keyboard_minus.png $TO_KEY/minus.png
cp $FROM_KEY/keyboard_m.png $TO_KEY/m.png
cp $FROM_KEY/keyboard_space.png $TO_KEY/nbsp.png
cp $FROM_KEY/keyboard_n.png $TO_KEY/n.png
cp $FROM_KEY/keyboard_numlock.png $TO_KEY/num.png
cp $FROM_KEY/keyboard_o.png $TO_KEY/o.png
cp $FROM_KEY/keyboard_page_down.png $TO_KEY/page_down.png
cp $FROM_KEY/keyboard_page_up.png $TO_KEY/page_up.png
cp $FROM_KEY/keyboard_pause.png $TO_KEY/pause.png
cp $FROM_KEY/keyboard_percent.png $TO_KEY/percent.png
cp $FROM_KEY/keyboard_period.png $TO_KEY/period.png
cp $FROM_KEY/keyboard_pipe.png $TO_KEY/pipe.png
cp $FROM_KEY/keyboard_plus.png $TO_KEY/plus.png
cp $FROM_KEY/keyboard_p.png $TO_KEY/p.png
cp $FROM_KEY/keyboard_print.png $TO_KEY/print.png
cp $FROM_KEY/keyboard_q.png $TO_KEY/q.png
cp $FROM_KEY/keyboard_question.png $TO_KEY/question.png
cp $FROM_KEY/keyboard_quote.png $TO_KEY/quote.png
cp $FROM_KEY/keyboard_bracket_close.png $TO_KEY/right_brace.png
cp $FROM_KEY/keyboard_right_bracket.png $TO_KEY/right_bracket.png
cp $FROM_KEY/keyboard_right_paren.png $TO_KEY/right_paren.png
cp $FROM_KEY/keyboard_arrow_right.png $TO_KEY/right.png
cp $FROM_KEY/keyboard_r.png $TO_KEY/r.png
cp $FROM_KEY/keyboard_scroll.png $TO_KEY/scroll.png
cp $FROM_KEY/keyboard_semicolon.png $TO_KEY/semicolon.png
cp $FROM_KEY/keyboard_shift.png $TO_KEY/shift.png
cp $FROM_KEY/keyboard_space.png $TO_KEY/space.png
cp $FROM_KEY/keyboard_s.png $TO_KEY/s.png
cp $FROM_KEY/keyboard_tab.png $TO_KEY/tab.png
cp $FROM_KEY/keyboard_tilde.png $TO_KEY/tilde.png
cp $FROM_KEY/keyboard_tile_0504.png $TO_KEY/tile_0504.png
cp $FROM_KEY/keyboard_t.png $TO_KEY/t.png
cp $FROM_KEY/keyboard_underscore.png $TO_KEY/underscore.png
cp $FROM_KEY/keyboard_u.png $TO_KEY/u.png
cp $FROM_KEY/keyboard_arrow_up.png $TO_KEY/up.png
cp $FROM_KEY/keyboard_v.png $TO_KEY/v.png
cp $FROM_KEY/keyboard_w.png $TO_KEY/w.png
cp $FROM_KEY/keyboard_x.png $TO_KEY/x.png
cp $FROM_KEY/keyboard_y.png $TO_KEY/y.png
cp $FROM_KEY/keyboard_z.png $TO_KEY/z.png


# Mouse
set FROM_MOUSE "$FROM/Keyboard & Mouse/$DEF"
set TO_MOUSE "$TO/mouse"

cp $FROM_MOUSE/mouse_left.png $TO_MOUSE/left.png
cp $FROM_MOUSE/mouse_scroll.png $TO_MOUSE/middle.png
cp $FROM_MOUSE/mouse_right.png $TO_MOUSE/right.png
cp $FROM_MOUSE/mouse_scroll_down.png $TO_MOUSE/wheel_down.png
cp $FROM_MOUSE/mouse_wheel_left.png $TO_MOUSE/wheel_left.png
cp $FROM_MOUSE/mouse_wheel_right.png $TO_MOUSE/wheel_right.png
cp $FROM_MOUSE/mouse_scroll_up.png $TO_MOUSE/wheel_up.png

# Nintendo
set FROM_NINTENDO "$FROM/Nintendo Switch/$DEF"
set TO_NINTENDO "$TO/nintendo"


cp $FROM_NINTENDO/switch_button_a.png           $TO_NINTENDO/a.png
cp $FROM_NINTENDO/switch_button_b.png           $TO_NINTENDO/b.png
cp $FROM_NINTENDO/switch_button_capture.png     $TO_NINTENDO/capture.png
cp $FROM_NINTENDO/switch_button_home.png        $TO_NINTENDO/home.png
cp $FROM_NINTENDO/switch_button_left_stick.png  $TO_NINTENDO/left_stick.png
cp $FROM_NINTENDO/switch_button_l.png           $TO_NINTENDO/l.png
cp $FROM_NINTENDO/switch_button_minus.png       $TO_NINTENDO/minus.png
cp $FROM_NINTENDO/switch_button_plus.png        $TO_NINTENDO/plus.png
cp $FROM_NINTENDO/switch_button_right_stick.png $TO_NINTENDO/right_stick.png
cp $FROM_NINTENDO/switch_button_r.png           $TO_NINTENDO/r.png
cp $FROM_NINTENDO/switch_button_x.png           $TO_NINTENDO/x.png
cp $FROM_NINTENDO/switch_button_y.png           $TO_NINTENDO/y.png
cp $FROM_NINTENDO/switch_button_zl.png          $TO_NINTENDO/zl.png
cp $FROM_NINTENDO/switch_button_zr.png          $TO_NINTENDO/zr.png
cp $FROM_NINTENDO/switch_dpad_up.png            $TO_NINTENDO/up.png
cp $FROM_NINTENDO/switch_dpad_down.png          $TO_NINTENDO/down.png
cp $FROM_NINTENDO/switch_dpad_left.png          $TO_NINTENDO/left.png
cp $FROM_NINTENDO/switch_dpad_right.png         $TO_NINTENDO/right.png
